const τεχνολογίες = [
  {
    εικόνα: '../assets/icons/Javascript.png',
    τίτλος: 'JS',
    alt: 'JS',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../assets/icons/HTML5.png',
    τίτλος: 'HTML5',
    alt: 'HTML5',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../assets/icons/CSS3.png',
    τίτλος: 'CSS3',
    alt: 'CSS3',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Express.png',
    τίτλος: 'Express',
    alt: 'Express',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Mongodb.png',
    τίτλος: 'MongoDB',
    alt: 'MongoDB',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Git.png',
    τίτλος: 'GIT',
    alt: 'GIT',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Nodejs.png',
    τίτλος: 'NodeJS',
    alt: 'NodeJS',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/React.png',
    τίτλος: 'React Nativ',
    alt: 'React Native',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/React Native.png',
    τίτλος: 'React Native',
    alt: 'React Native',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Npm.png',
    τίτλος: 'NPM',
    alt: 'NPM',
    width: '43',
    height: '43',
  },
  {
    εικόνα: '../../public/icons/Firebase.png',
    τίτλος: 'Firebase',
    alt: 'Firebase',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Github.png',
    τίτλος: 'Github',
    alt: 'Github',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/VSCode.png',
    τίτλος: 'VSCode',
    alt: 'VSCode',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Yarn.png',
    τίτλος: 'Yarn',
    alt: 'Yarn',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Redux.png',
    τίτλος: 'Redux',
    alt: 'Redux',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Mysql.png',
    τίτλος: 'MySQL',
    alt: 'MySQL ',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Swift.png',
    τίτλος: 'Swift',
    alt: 'Swift',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Bootstrap.png',
    τίτλος: 'Bootstrap',
    alt: 'Bootstrap',
    width: '41',
    height: '41',
  },
  {
    εικόνα: '../../public/icons/Codepen.png',
    τίτλος: 'Codepen',
    alt: 'Codepen',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Webpack.png',
    τίτλος: 'Webpack',
    alt: 'Webpack',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Mongodb.png',
    τίτλος: 'Firebase',
    alt: 'Firebase',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Mongodb.png',
    τίτλος: 'WebPack',
    alt: 'WebPack',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Mongodb.png',
    τίτλος: 'Safari',
    alt: 'Safari',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Mongodb.png',
    τίτλος: 'Chrome',
    alt: 'Chrome',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Mongodb.png',
    τίτλος: 'Firefox',
    alt: 'Firefox',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Mongodb.png',
    τίτλος: 'Opera',
    alt: 'Opera',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Mongodb.png',
    τίτλος: 'WordPress',
    alt: 'WordPress',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Mongodb.png',
    τίτλος: 'WIX',
    alt: 'WIX',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Mongodb.png',
    τίτλος: 'WPML',
    alt: 'WPML',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Mongodb.png',
    τίτλος: 'WooCommerce',
    alt: 'WooCommerce',
    width: '80',
    height: '80',
  },
  {
    εικόνα: '../../public/icons/Mongodb.png',
    τίτλος: 'Swift',
    alt: 'Swift',
    width: '80',
    height: '80',
  },
];

export default τεχνολογίες;
